/*文章单元表*/
CREATE TABLE cpub_section(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
title VARCHAR(255) NOT NULL,
  alias VARCHAR(255) NOT NULL ,
  description TEXT NOT NULL ,
  published TINYINT(1) NOT NULL DEFAULT 0,
  torder INT NOT NULL DEFAULT 0,
  aceess TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  params TEXT NOT NULL
)ENGINE = MYISAM;

/*文章分类表*/
CREATE TABLE cpub_category(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  title VARCHAR(255) NOT NULL,
  alias VARCHAR(255) NOT NULL ,
  description TEXT NOT NULL ,
  published TINYINT(1) NOT NULL ,
  torder INT NOT NULL ,
  access TINYINT(3) UNSIGNED NOT NULL ,
  sectionid INT UNSIGNED NOT NULL ,
  params TEXT NOT NULL
)ENGINE = MYISAM;

/*文章表*/
CREATE TABLE cpub_article(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  title VARCHAR(255) NOT NULL,
  alias VARCHAR(255) NOT NULL ,
  title_alias VARCHAR(255) NOT NULL ,
  introtext MEDIUMTEXT NOT NULL ,
  published TINYINT(1) NOT NULL DEFAULT 0,
  sectionid INT UNSIGNED NOT NULL ,
  catid INT UNSIGNED NOT NULL ,
  created DATE NOT NULL ,
  created_by INT UNSIGNED NOT NULL ,
  modefied DATETIME NOT NULL ,
  modefied_by INT UNSIGNED NOT NULL ,
  published_up DATETIME NOT NULL ,
  published_down DATETIME NOT NULL ,
  torder INT NOT NULL DEFAULT 0,
  access TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  metakey TEXT NOT NULL ,
  metadesc TEXT NOT NULL ,
  hits INT UNSIGNED NOT NULL ,
  metadata TEXT NOT NULL ,
  params TEXT NOT NULL ,
  INDEX (sectionid),
  INDEX (catid),
  INDEX (created_by)
)ENGINE = MYISAM;

/*菜单表*/
CREATE TABLE cpub_menu(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  title VARCHAR(255) NOT NULL ,
  menutype VARCHAR(75) NOT NULL ,
  description TEXT NOT NULL ,
  UNIQUE(menutype)
)ENGINE = MYISAM;

/*菜单组件表*/
CREATE TABLE cpub_component(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(50) NOT NULL ,
  link VARCHAR(255) NOT NULL ,
  toption VARCHAR(50) NOT NULL ,
  torder INT NOT NULL DEFAULT '0',
  params TEXT NOT NULL ,
  enabled TINYINT(4) NOT NULL DEFAULT 1
)ENGINE MYISAM;

/*菜单项表*/
CREATE TABLE cpub_menu_item(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(255) NOT NULL ,
  menuid INT UNSIGNED NOT NULL ,
  alias VARCHAR(255) NOT NULL ,
  link TEXT NOT NULL ,
  type VARCHAR(50) NOT NULL ,
  published TINYINT(1) NOT NULL DEFAULT '0',
  pid INT UNSIGNED NOT NULL DEFAULT '0',
  path TEXT NOT NULL ,
  componentid INT UNSIGNED NOT NULL ,
  torder INT NOT NULL DEFAULT '0',
  browserNav TINYINT(4) NOT NULL DEFAULT '0',
  access TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  params TEXT NOT NULL
)ENGINE MYISAM;



